language: node_js

node_js: 10

install:
  - npm ci --ignore-scripts

script:
  - nps build
  - npx nps test.coverage

after_success:
  - npx codacy-coverage -v < ./coverage/lcov.info

cache:
  directories:
    - node_modules
